"""Auto-remediation for failing health gates.

Reporting a problem and leaving it is a complaint. Every finding in ``health``
carries a remedy, so the ones that are mechanically fixable should just be fixed.

The split matters:

- **Safe**: regenerating a derived file, deleting a build artifact, restoring a
  scaffold directory. The output is fully determined by the input.
- **Unsafe**: writing prose, choosing what a skill's Completion section should
  demand, deciding whether a doc should be linked or archived. Guessing here
  produces plausible-looking wrong content, which is worse than a red gate.

``awino fix`` performs the safe set and reports the unsafe set as work for a
human or an agent with judgement.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path

from smith.paths import SmithPaths


class Outcome(StrEnum):
    FIXED = "FIXED"
    SKIPPED = "SKIPPED"
    MANUAL = "MANUAL"


@dataclass(frozen=True)
class Repair:
    check: str
    outcome: Outcome
    detail: str


def _fixed(check: str, detail: str) -> Repair:
    return Repair(check, Outcome.FIXED, detail)


def _manual(check: str, detail: str) -> Repair:
    return Repair(check, Outcome.MANUAL, detail)


def _skipped(check: str, detail: str) -> Repair:
    return Repair(check, Outcome.SKIPPED, detail)


# ── derived files, always safe to regenerate ─────────────────────────────────


def skill_index(paths: SmithPaths) -> str:
    """Build the skill index from the filesystem.

    The index is derived, never authored. A hand-maintained list of skills drifts
    the moment someone adds a directory, and a router that lies about what exists
    is worse than no router.
    """
    rows: list[tuple[str, str, str]] = []
    for skill in sorted(paths.skills.glob("awino-*/SKILL.md")):
        text = skill.read_text(encoding="utf-8")
        name = _frontmatter_value(text, "name") or skill.parent.name
        description = _frontmatter_value(text, "description") or "(no description)"
        rows.append((name, description, f"../skills/{skill.parent.name}/SKILL.md"))

    lines = [
        "# Skills",
        "",
        "Generated by `awino fix`. Do not edit by hand: run `just fix` after adding a skill.",
        "",
        f"{len(rows)} canonical A.W.I.N.O. skill(s).",
        "",
        "| Skill | Purpose |",
        "| --- | --- |",
    ]
    for name, description, link in rows:
        summary = description.split(". ")[0].rstrip(".")
        if len(summary) > 110:
            summary = summary[:107] + "..."
        lines.append(f"| [`{name}`]({link}) | {summary} |")
    lines += [
        "",
        "## Invocation",
        "",
        "```bash",
        "awino gate skill <name>   # record that a skill was used, so usage is auditable",
        "```",
        "",
        "Every skill is validated by `awino validate skills`. A skill missing its",
        "Failure Modes or Completion section blocks the `artifacts` gate.",
        "",
        "## Compatibility",
        "",
        "Deprecated `smith-*` skill aliases remain resolvable for existing integrations,",
        "but they are not canonical skills and are intentionally omitted from this index.",
        "",
    ]
    return "\n".join(lines)


def _frontmatter_value(text: str, key: str) -> str | None:
    match = re.search(rf"^{key}:\s*(.+)$", text, re.MULTILINE)
    return match.group(1).strip() if match else None


def plugin_skill_list(paths: SmithPaths) -> list[str]:
    return sorted(p.parent.name for p in paths.skills.glob("awino-*/SKILL.md"))


# ── the repairs ──────────────────────────────────────────────────────────────


def fix_skill_index(paths: SmithPaths) -> Repair:
    target = paths.docs / "skills.md"
    wanted = skill_index(paths)
    if target.is_file() and target.read_text(encoding="utf-8") == wanted:
        return _skipped("skill_index", "already current")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(wanted, encoding="utf-8")
    count = len(plugin_skill_list(paths))
    return _fixed("skill_index", f"regenerated docs/skills.md from {count} skill(s)")


def fix_doc_links(paths: SmithPaths) -> Repair:
    """Add a Docs-table row for any doc the README does not mention.

    Adding a link is safe because the target exists and its title is derivable.
    Deciding a doc should be *deleted* instead is judgement, so that stays manual.
    """
    readme = paths.root / "README.md"
    if not readme.is_file():
        return _manual("doc_links", "no README.md to repair")
    body = readme.read_text(encoding="utf-8")
    docs = sorted(paths.docs.glob("*.md"))
    # A directory README documents its own folder and is not a topic doc.
    orphans = [d for d in docs if d.name != "README.md" and f"docs/{d.name}" not in body]
    if not orphans:
        return _skipped("doc_links", "every doc already linked")

    marker = "## Docs"
    if marker not in body:
        return _manual(
            "doc_links",
            f"{len(orphans)} unlinked doc(s) and no '## Docs' section to extend: "
            f"{', '.join(d.name for d in orphans)}",
        )

    rows = []
    for doc in orphans:
        title = _first_heading(doc) or doc.stem.replace("-", " ").title()
        rows.append(f"| [docs/{doc.name}](docs/{doc.name}) | {title} |")

    lines = body.splitlines()
    start = next(i for i, ln in enumerate(lines) if ln.strip() == marker)
    insert_at = len(lines)
    for index in range(start + 1, len(lines)):
        if lines[index].startswith("---") or lines[index].startswith("## "):
            insert_at = index
            break
        if lines[index].startswith("|"):
            insert_at = index + 1
    lines[insert_at:insert_at] = rows
    readme.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return _fixed(
        "doc_links", f"linked {len(orphans)} doc(s): {', '.join(d.name for d in orphans)}"
    )


def _first_heading(path: Path) -> str | None:
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return None


def fix_broken_doc_links(paths: SmithPaths) -> Repair:
    """A README link to a nonexistent file is a lie, but only a human knows which
    way to resolve it: write the doc, or drop the promise."""
    readme = paths.root / "README.md"
    if not readme.is_file():
        return _skipped("broken_links", "no README.md")
    body = readme.read_text(encoding="utf-8")
    broken = [
        link
        for link in re.findall(r"\]\((docs/[^)#]+\.md)\)", body)
        if not (paths.root / link).is_file()
    ]
    if not broken:
        return _skipped("broken_links", "no broken links")
    return _manual(
        "broken_links",
        f"README promises {', '.join(broken)}. Write the doc or remove the link, do not guess content.",
    )


def fix_scaffold(paths: SmithPaths) -> Repair:
    created = paths.ensure_scaffold()
    if not created:
        return _skipped("scaffold", "all directories present")
    return _fixed("scaffold", f"created {', '.join(d.name for d in created)}")


def fix_gitkeeps(paths: SmithPaths) -> Repair:
    """Directories that are meant to be empty must say so, or hygiene flags them."""
    intentional = [paths.expertise, paths.emitted, paths.specs, paths.archive]
    added: list[str] = []
    for directory in intentional:
        if not directory.is_dir():
            continue
        if any(directory.iterdir()):
            continue
        (directory / ".gitkeep").write_text("", encoding="utf-8")
        added.append(directory.name)
    if not added:
        return _skipped("gitkeeps", "no empty directories needing a marker")
    return _fixed("gitkeeps", f"marked {', '.join(added)} as intentionally empty")


def fix_clone_freshness(paths: SmithPaths) -> Repair:
    """Fast-forward a clean-but-behind clone; report anything less certain.

    A clean clone that is only behind its own remote is fully deterministic
    to fix: fast-forwarding is catching up to already-published history,
    which is the exact case this repo's own lessons landed in a stale
    duplicate clone twice - reported as a WARN nobody acted on until a human
    went looking for it. Dirty or diverged state is refused, not guessed at,
    matching updater.update_preflight()'s existing safety contract; a human
    resolving a real merge conflict is not something a mechanical repair
    should attempt.
    """
    import shutil as _shutil

    from smith.health import run_command

    if _shutil.which("git") is None:
        return _skipped("clone_freshness", "git not on PATH")
    if run_command(["git", "rev-parse", "--git-dir"], paths.root)[0] != 0:
        return _skipped("clone_freshness", "not a git checkout")

    status_code, status_out = run_command(["git", "status", "--porcelain=v1", "-uno"], paths.root)
    if status_code == 0 and status_out.strip():
        return Repair(
            "clone_freshness",
            Outcome.MANUAL,
            "uncommitted tracked changes; commit or stash before pulling",
        )

    fetch_code, _ = run_command(
        ["git", "-c", "credential.interactive=never", "fetch"], paths.root, timeout=15
    )
    if fetch_code != 0:
        return _skipped("clone_freshness", "could not reach the remote")

    ahead_code, ahead_out = run_command(["git", "rev-list", "--count", "@{u}..HEAD"], paths.root)
    behind_code, behind_out = run_command(["git", "rev-list", "--count", "HEAD..@{u}"], paths.root)
    if ahead_code != 0 or behind_code != 0:
        return _skipped("clone_freshness", "no upstream tracking branch configured")

    ahead = int(ahead_out.strip() or 0)
    behind = int(behind_out.strip() or 0)
    if ahead:
        return Repair(
            "clone_freshness",
            Outcome.MANUAL,
            f"{ahead} local commit(s) not yet pushed; push before relying on this clone",
        )
    if not behind:
        return _skipped("clone_freshness", "already up to date with its remote")

    pull_code, pull_out = run_command(["git", "pull", "--ff-only"], paths.root)
    if pull_code != 0:
        return Repair(
            "clone_freshness",
            Outcome.MANUAL,
            f"fast-forward pull failed: {pull_out.strip()[:200]}",
        )
    return _fixed("clone_freshness", f"fast-forwarded {behind} commit(s) from origin")


def fix_disposable(paths: SmithPaths) -> Repair:
    from smith.knowledge import KnowledgeStore
    from smith.tidy import Finding, Tidier

    tidier = Tidier(paths)
    items = tidier.scan(orphaned_cache=KnowledgeStore(paths).orphaned_cache())
    removable = [i for i in items if i.kind in {Finding.DISPOSABLE, Finding.ORPHANED_CACHE}]
    if not removable:
        return _skipped("disposable", "nothing to clean")
    removed = tidier.clean(removable)
    return _fixed("disposable", f"removed {len(removed)} regenerable artifact(s)")


def fix_stray_root(paths: SmithPaths) -> Repair:
    """Stray root files get archived, which is reversible, never deleted."""
    from smith.tidy import Finding, Tidier

    tidier = Tidier(paths)
    stray = [
        i for i in tidier.scan() if i.kind in {Finding.STRAY_ROOT_FILE, Finding.STRAY_ROOT_DIR}
    ]
    if not stray:
        return _skipped("stray_root", "root is clean")
    destination, moved = tidier.archive(stray)
    if not moved:
        return _manual("stray_root", f"{len(stray)} stray item(s) could not be archived")
    return _fixed("stray_root", f"archived {len(moved)} item(s) to {destination.name}")


def fix_artifacts(paths: SmithPaths) -> Repair:
    """Report invalid artifacts precisely. Never rewrite their prose.

    A skill missing its Completion section needs a real verification command
    chosen by someone who knows what the skill does. Synthesising one produces a
    gate that passes the validator and means nothing.
    """
    from smith.validate import discover, validate_file

    broken: list[str] = []
    for file in discover([paths.skills, paths.agents, paths.emitted]):
        report = validate_file(file)
        if report.ok():
            continue
        names = ", ".join(c.name for c in report.failures)
        broken.append(f"{file.parent.name}/{file.name}: {names}")
    if not broken:
        return _skipped("artifacts", "all valid")
    return _manual("artifacts", "; ".join(broken))


def fix_memory_format(paths: SmithPaths) -> Repair:
    """Undated lessons are reported, not rewritten: only the author knows the date."""
    if not paths.lessons.is_file():
        paths.lessons.parent.mkdir(parents=True, exist_ok=True)
        paths.lessons.write_text(
            "# Lessons - binding prevention rules\n\n"
            "**Append-only.** To revise, mark the old line `[SUPERSEDED yyyy-mm-dd]`\n"
            "and append the new one below it.\n\n"
            "Format:\n\n"
            "```\n- [yyyy-mm-dd] `FAILURE_MODE` the rule as an imperative. (surface: prompt|model|context|tools)\n```\n\n"
            "---\n\n## Rules\n\n---\n\n## Superseded\n",
            encoding="utf-8",
        )
        return _fixed("memory_format", "created memory/lessons.md with the required shape")

    from smith.health import _strip_code_fences

    prose = _strip_code_fences(paths.lessons.read_text(encoding="utf-8"))
    malformed = [
        ln
        for ln in prose.splitlines()
        if ln.startswith("- ") and not re.match(r"^- \[\d{4}-\d{2}-\d{2}\]", ln)
    ]
    if not malformed:
        return _skipped("memory_format", "ledger well formed")
    return _manual(
        "memory_format",
        f"{len(malformed)} undated lesson(s), first is {malformed[0][:60]!r}. Add the real date.",
    )


def fix_folder_docs(paths: SmithPaths) -> Repair:
    """Give every meaningful directory a FAIR README.

    Known directories get real content. Unknown ones get a marked stub with
    explicit TODOs, because a confident generated guess about a directory's
    purpose is worse than an obvious gap.
    """
    from smith import fair

    written, _ = fair.write_missing(paths.root)
    remaining = fair.stubs(paths.root)
    if not written:
        if remaining:
            return _manual("folder_docs", f"{len(remaining)} generated stub(s) still contain TODOs")
        return _skipped("folder_docs", "every directory documented")
    detail = f"wrote {len(written)} README(s)"
    if remaining:
        detail += f", {len(remaining)} contain TODOs needing a human"
    return _fixed("folder_docs", detail)


SAFE_REPAIRS = (
    fix_scaffold,
    fix_gitkeeps,
    fix_skill_index,
    fix_folder_docs,
    fix_doc_links,
    fix_disposable,
    fix_clone_freshness,
)

REPORT_ONLY = (
    fix_broken_doc_links,
    fix_artifacts,
    fix_memory_format,
)


def run_fixes(paths: SmithPaths, *, aggressive: bool = False) -> list[Repair]:
    """Apply safe repairs, then report what needs judgement.

    ``aggressive`` adds archiving stray root items, which moves files and so is
    opt-in rather than default.
    """
    repairs = [repair(paths) for repair in SAFE_REPAIRS]
    if aggressive:
        repairs.append(fix_stray_root(paths))
    repairs += [repair(paths) for repair in REPORT_ONLY]
    return repairs
